server:
    port: 8080
    address: localhost
jdbc:
    driverClass: com.mysql.jdbc.Driver  
    url: jdbc:mysql://127.0.0.1:3306/testcache?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root  
    password: xjh199409  
    
